/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Classes.User;
import Classes.Registrasi;
import java.awt.FontFormatException;
import java.awt.Frame;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author baru_san
 */
public class BuatAkun extends javax.swing.JFrame {

    /**
     * Creates new form BuatAkun
     */
    public BuatAkun(java.awt.Frame parent, Registrasi regis){
        this.parent = parent;
        this.user = regis;
        this.regis = regis;
        
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonBuatAkun = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        FieldNama = new javax.swing.JTextField();
        LabelNama = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonBuatAkun.setBackground(new java.awt.Color(0, 200, 255));
        ButtonBuatAkun.setText("Buat Akun");
        ButtonBuatAkun.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        ButtonBuatAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuatAkunActionPerformed(evt);
            }
        });

        FieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldNamaActionPerformed(evt);
            }
        });

        LabelNama.setText("Masukkan Nama Anda");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNama))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(LabelNama)
                .addGap(18, 18, 18)
                .addComponent(FieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ButtonBuatAkun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(ButtonBuatAkun))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonBuatAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuatAkunActionPerformed

        if(regis.getNama().equals("")){
            try {
                createAccountAction();
            } catch (FontFormatException ex) {
                Logger.getLogger(BuatAkun.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_ButtonBuatAkunActionPerformed

    private void FieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldNamaActionPerformed

    private void createAccountAction() throws FontFormatException {
        String nama = FieldNama.getText().trim();
        if(nama.equals("")) {
            nama = "User-" + regis.getEmail();
        }
        
        regis.setNama(nama);
        
        try{
            regis.registrasiUser();
        } catch (IOException ex) {
            Logger.getLogger(BuatAkun.class.getName()).log(Level.SEVERE, null, ex);
        }
        
//        int kondisi = 2;
//        PopUp popbeli = new PopUp(kondisi);
//        popbeli.setLocationRelativeTo(null);
//        popbeli.setVisible(true);
        Login login = new Login();
        login.setVisible(true);
        parent.dispose();
        dispose();
        
        
    }
    
    private final java.awt.Frame parent;
    private User user;
    private Registrasi regis;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBuatAkun;
    private javax.swing.JTextField FieldNama;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
