/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Classes.User;
import Databases.Database;
import java.util.List;

/**
 *
 * @author baru_san
 */
public class Dashboard extends javax.swing.JFrame {
    private User user;
    private List<String[]> datamk;
    /**
     * Creates new form Dashboard
     */
    public Dashboard(User user) {
//        System.out.println(user.getNama());
        this.user = user;  
        Database db = new Database();
        
        this.datamk = db.DataMK(user.getNama());
        for (String[] data : datamk) {
           System.out.println(data[0]);
           System.out.println(data[1]);
           System.out.println(data[2]);
        }
        
        initComponents();
    }
    
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tambahMKBtn = new javax.swing.JButton();
        Nama = new javax.swing.JLabel();
        Logoutbtn = new javax.swing.JButton();
        panelAB = new javax.swing.JPanel();
        panelABbackground = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1080, 820));

        tambahMKBtn.setText("Tambah MK");
        tambahMKBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahMKBtnActionPerformed(evt);
            }
        });

        Nama.setText("Hello, " + user.getNama());

        Logoutbtn.setText("Log out");
        Logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Nama)
                .addGap(109, 109, 109)
                .addComponent(Logoutbtn)
                .addGap(80, 80, 80)
                .addComponent(tambahMKBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahMKBtn)
                    .addComponent(Nama)
                    .addComponent(Logoutbtn))
                .addGap(33, 33, 33))
        );

        panelABbackground.setBackground(new java.awt.Color(255, 255, 255));
        panelABbackground.setMaximumSize(new java.awt.Dimension(32767, 25));
        panelABbackground.setLayout(new javax.swing.BoxLayout(panelABbackground, javax.swing.BoxLayout.LINE_AXIS));
        panelABbackground.setMinimumSize(new java.awt.Dimension(0, 25));
        panelABbackground.setLayout(new javax.swing.BoxLayout(panelABbackground, javax.swing.BoxLayout.PAGE_AXIS));

        //panelAB.add(panelABbackground, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout panelABLayout = new javax.swing.GroupLayout(panelAB);
        panelAB.setLayout(panelABLayout);
        panelABLayout.setHorizontalGroup(
            panelABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelABLayout.createSequentialGroup()
                .addComponent(panelABbackground, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelABLayout.setVerticalGroup(
            panelABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelABLayout.createSequentialGroup()
                .addComponent(panelABbackground, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        ListMK(this.datamk);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelAB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahMKBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahMKBtnActionPerformed
        TambahMK mk = new TambahMK(user);
        mk.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_tambahMKBtnActionPerformed

    private void LogoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutbtnActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutbtnActionPerformed

    private void ListMK(List<String[]> datamk) {
        int size = 10;
        
        panelLSLoop = new javax.swing.JPanel[size];
        fillerLSLoopPre = new javax.swing.Box.Filler[size];
        labelLSLoop1 = new javax.swing.JLabel[size];
        fillerLSLoop = new javax.swing.Box.Filler[size];
        fillerLSLoop2 = new javax.swing.Box.Filler[size];
        fillerLSLoopPos = new javax.swing.Box.Filler[size];
        buybtnLoop = new javax.swing.JButton[size];
        labelJamLoop = new javax.swing.JLabel[size];
        labelRuangLoop = new javax.swing.JLabel[size];

            panelLSLoop[0] = new javax.swing.JPanel();
            fillerLSLoopPre[0] = new javax.swing.Box.Filler(new java.awt.Dimension(250, 0), new java.awt.Dimension(250, 0), new java.awt.Dimension(250, 32767));
            labelLSLoop1[0] = new javax.swing.JLabel();
            fillerLSLoop[0] = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
            fillerLSLoop2[0] = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
            fillerLSLoopPos[0] = new javax.swing.Box.Filler(new java.awt.Dimension(250, 0), new java.awt.Dimension(250,0), new java.awt.Dimension(250, 32767));
            buybtnLoop[0] = new javax.swing.JButton();
            labelJamLoop[0] = new javax.swing.JLabel();
            labelRuangLoop[0] = new javax.swing.JLabel();

            panelLSLoop[0].setBackground(new java.awt.Color(255, 255, 255));
            panelLSLoop[0].setMaximumSize(new java.awt.Dimension(32767, 30));
            panelLSLoop[0].setMinimumSize(new java.awt.Dimension(0, 30));
            panelLSLoop[0].setLayout(new javax.swing.BoxLayout(panelLSLoop[0], javax.swing.BoxLayout.LINE_AXIS));
            panelLSLoop[0].add(fillerLSLoopPre[0]);

            labelLSLoop1[0].setText("Mata Kuliah");
            labelLSLoop1[0].setMaximumSize(new java.awt.Dimension(600, 30));
            labelLSLoop1[0].setMinimumSize(new java.awt.Dimension(500, 30));
            panelLSLoop[0].add(labelLSLoop1[0]);
            panelLSLoop[0].add(fillerLSLoop[0]);
            
            labelJamLoop[0].setText("Jam");
            labelJamLoop[0].setMaximumSize(new java.awt.Dimension(600, 30));
            labelJamLoop[0].setMinimumSize(new java.awt.Dimension(500, 30));
            panelLSLoop[0].add(labelJamLoop[0]);
            panelLSLoop[0].add(fillerLSLoop2[0]);
//            
            labelRuangLoop[0].setText("Ruang");
            labelRuangLoop[0].setMaximumSize(new java.awt.Dimension(600, 30));
            labelRuangLoop[0].setMinimumSize(new java.awt.Dimension(500, 30));
            panelLSLoop[0].add(labelRuangLoop[0]);
            panelLSLoop[0].add(fillerLSLoopPos[0]);


            panelLSLoop[0].setName("" + 0);



            panelABbackground.add(panelLSLoop[0]);
        
        for (String[] data : datamk) {
            int i = 1 ;
            panelLSLoop[i] = new javax.swing.JPanel();
            fillerLSLoopPre[i] = new javax.swing.Box.Filler(new java.awt.Dimension(250, 0), new java.awt.Dimension(250, 0), new java.awt.Dimension(250, 32767));
            labelLSLoop1[i] = new javax.swing.JLabel();
            fillerLSLoop[i] = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
            fillerLSLoop2[i] = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
            fillerLSLoopPos[i] = new javax.swing.Box.Filler(new java.awt.Dimension(250, 0), new java.awt.Dimension(250,0), new java.awt.Dimension(250, 32767));
            buybtnLoop[i] = new javax.swing.JButton();
            labelJamLoop[i] = new javax.swing.JLabel();
            labelRuangLoop[i] = new javax.swing.JLabel();

            panelLSLoop[i].setBackground(new java.awt.Color(255, 255, 255));
            panelLSLoop[i].setMaximumSize(new java.awt.Dimension(32767, 30));
            panelLSLoop[i].setMinimumSize(new java.awt.Dimension(0, 30));
            panelLSLoop[i].setLayout(new javax.swing.BoxLayout(panelLSLoop[i], javax.swing.BoxLayout.LINE_AXIS));
            panelLSLoop[i].add(fillerLSLoopPre[i]);

            labelLSLoop1[i].setText(data[1]);
            labelLSLoop1[i].setMaximumSize(new java.awt.Dimension(600, 30));
            labelLSLoop1[i].setMinimumSize(new java.awt.Dimension(500, 30));
            panelLSLoop[i].add(labelLSLoop1[i]);
            panelLSLoop[i].add(fillerLSLoop[i]);
            
            labelJamLoop[i].setText(data[2]);
            labelJamLoop[i].setMaximumSize(new java.awt.Dimension(600, 30));
            labelJamLoop[i].setMinimumSize(new java.awt.Dimension(500, 30));
            panelLSLoop[i].add(labelJamLoop[i]);
            panelLSLoop[i].add(fillerLSLoop2[i]);
//            
            labelRuangLoop[i].setText(data[3]);
            labelRuangLoop[i].setMaximumSize(new java.awt.Dimension(600, 30));
            labelRuangLoop[i].setMinimumSize(new java.awt.Dimension(500, 30));
            panelLSLoop[i].add(labelRuangLoop[i]);
            panelLSLoop[i].add(fillerLSLoopPos[i]);


            panelLSLoop[i].setName("" + i);



            panelABbackground.add(panelLSLoop[i]);
            i++;
        }
    }

        // Variables for Looping Listed Books
    private javax.swing.JPanel[] panelLSLoop;
    private javax.swing.Box.Filler[] fillerLSLoop;
    private javax.swing.Box.Filler[] fillerLSLoop2;
    private javax.swing.Box.Filler[] fillerLSLoopPre;
    private javax.swing.Box.Filler[] fillerLSLoopPos;
    private javax.swing.JLabel[] labelLSLoop1;
    private javax.swing.JButton[] buybtnLoop;
    private javax.swing.JLabel[] labelJamLoop;
    private javax.swing.JLabel[] labelRuangLoop;

//    private final User user;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logoutbtn;
    private javax.swing.JLabel Nama;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelAB;
    private javax.swing.JPanel panelABbackground;
    private javax.swing.JButton tambahMKBtn;
    // End of variables declaration//GEN-END:variables
}
