/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Classes.Mata_Kuliah;
import Classes.User;
import Databases.Database;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author baru_san
 */
public class TambahMK extends javax.swing.JFrame {
    private User user;

    /**
     * Creates new form TambahMK
     */
    public TambahMK(User user) {
        initComponents();
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tmbhMKLabel = new javax.swing.JLabel();
        JamLabel = new javax.swing.JLabel();
        MKField = new javax.swing.JTextField();
        MKLabel = new javax.swing.JLabel();
        JamField = new javax.swing.JTextField();
        RuangLabel = new javax.swing.JLabel();
        RuangField = new javax.swing.JTextField();
        submitMKbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tmbhMKLabel.setText("Form Tambah MK");

        JamLabel.setText("Jam");

        MKField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MKFieldActionPerformed(evt);
            }
        });

        MKLabel.setText("Nama MK");

        JamField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JamFieldActionPerformed(evt);
            }
        });

        RuangLabel.setText("Ruang");

        submitMKbtn.setText("Submit");
        submitMKbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitMKbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(tmbhMKLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(submitMKbtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RuangField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JamLabel)
                                .addComponent(RuangLabel)
                                .addComponent(MKLabel)
                                .addComponent(MKField, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                .addComponent(JamField)))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(tmbhMKLabel)
                .addGap(43, 43, 43)
                .addComponent(MKLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MKField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JamLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RuangLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RuangField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(submitMKbtn)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MKFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MKFieldActionPerformed

    }//GEN-LAST:event_MKFieldActionPerformed

    private void submitMKbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitMKbtnActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        String nama = MKField.getText().trim();
        String jam = JamField.getText().trim();
        String ruang = RuangField.getText().trim();
        
        try {
            if(nama.equals("") || jam.equals("") || ruang.equals("")){
                MKLabel.setText("Isi data dengan lengkap.");
                MKLabel.setForeground(java.awt.Color.red);

            }
            else{
                addData(new Mata_Kuliah(user.getNama(),nama, jam, ruang));
                Dashboard dashboard = new Dashboard(user);
                dashboard.setVisible(true);
                
                dispose();
            }
        } catch (IOException ex){
            Logger.getLogger(Mata_Kuliah.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitMKbtnActionPerformed

    private void JamFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JamFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JamFieldActionPerformed

    public void addData(Mata_Kuliah mk) throws IOException{
        Database db = new Database();
        db.tulisDataMK(mk.getNamaUser(),mk.getNamaMK(), mk.getJam(), mk.getRuang());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JamField;
    private javax.swing.JLabel JamLabel;
    private javax.swing.JTextField MKField;
    private javax.swing.JLabel MKLabel;
    private javax.swing.JTextField RuangField;
    private javax.swing.JLabel RuangLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton submitMKbtn;
    private javax.swing.JLabel tmbhMKLabel;
    // End of variables declaration//GEN-END:variables
}
